---
-
  hosts: all
  tasks:
    - name: copy bash file
      copy:
        src: ./reados.sh
        dest: /tmp/reados.sh
        owner: docker
        group: docker
        mode: 01777
    
    - name: script exec
      command: /tmp/reados.sh
      register: var

    - name: data saving
      debug:
        msg: 
          - "Standard input: {{var.stdout}}"
          - "Standard output: {{var.rc}}"
          - "Code: {{var.stderr}}"
---